import React, { useState, useEffect, useCallback } from 'react';
import { ChevronLeft, ChevronRight, Share2, Download, Sparkles, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';

interface Teaching {
  category: string;
  text: string;
  source: string;
  theme: string;
}

interface TeachingCard {
  teaching: Teaching;
  imageUrl: string | null;
  loading: boolean;
}

const DailyTeachingsCarousel: React.FC = () => {
  const [teachings, setTeachings] = useState<Teaching[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [cards, setCards] = useState<Map<number, TeachingCard>>(new Map());
  const [isGenerating, setIsGenerating] = useState(false);

  // Get today's Hijri date
  const [hijriDate, setHijriDate] = useState<string>('');

  useEffect(() => {
    const fetchHijriDate = async () => {
      try {
        const today = new Date();
        const timestamp = Math.floor(today.getTime() / 1000);
        const response = await fetch(
          `https://api.aladhan.com/v1/timings/${timestamp}?latitude=21.4225&longitude=39.8262&method=2`
        );
        const data = await response.json();
        if (data.code === 200) {
          const hijri = data.data.date.hijri;
          setHijriDate(`${hijri.day} ${hijri.month.en} ${hijri.year} AH`);
        }
      } catch (error) {
        console.error('Error fetching Hijri date:', error);
      }
    };
    fetchHijriDate();
  }, []);

  // Fetch teachings on mount
  useEffect(() => {
    const fetchTeachings = async () => {
      try {
        const { data, error } = await supabase.functions.invoke('mia-daily-teaching', {
          body: { action: 'get-teachings' },
        });

        if (error) throw error;
        if (data?.teachings) {
          setTeachings(data.teachings);
          // Set initial index based on day of year for daily rotation
          const dayOfYear = Math.floor(
            (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
          );
          setCurrentIndex(dayOfYear % data.teachings.length);
        }
      } catch (error) {
        console.error('Error fetching teachings:', error);
      }
    };
    fetchTeachings();
  }, []);

  const generateImage = useCallback(async (index: number) => {
    if (cards.get(index)?.imageUrl || cards.get(index)?.loading) return;

    setCards(prev => new Map(prev).set(index, {
      teaching: teachings[index],
      imageUrl: null,
      loading: true,
    }));

    try {
      const { data, error } = await supabase.functions.invoke('mia-daily-teaching', {
        body: { action: 'generate-image', teachingIndex: index },
      });

      if (error) throw error;

      setCards(prev => new Map(prev).set(index, {
        teaching: teachings[index],
        imageUrl: data?.imageUrl || null,
        loading: false,
      }));
    } catch (error) {
      console.error('Error generating image:', error);
      setCards(prev => new Map(prev).set(index, {
        teaching: teachings[index],
        imageUrl: null,
        loading: false,
      }));
      toast.error('Failed to generate image');
    }
  }, [teachings, cards]);

  // Generate image for current teaching
  useEffect(() => {
    if (teachings.length > 0 && !cards.has(currentIndex)) {
      generateImage(currentIndex);
    }
  }, [currentIndex, teachings, cards, generateImage]);

  const goToNext = () => {
    setCurrentIndex(prev => (prev + 1) % teachings.length);
  };

  const goToPrevious = () => {
    setCurrentIndex(prev => (prev - 1 + teachings.length) % teachings.length);
  };

  const regenerateImage = async () => {
    setIsGenerating(true);
    setCards(prev => {
      const newMap = new Map(prev);
      newMap.delete(currentIndex);
      return newMap;
    });
    await generateImage(currentIndex);
    setIsGenerating(false);
  };

  const handleShare = async () => {
    const currentCard = cards.get(currentIndex);
    const teaching = teachings[currentIndex];
    
    if (!teaching) return;

    const shareText = `"${teaching.text}"\n\n— ${teaching.source}\n\n📅 ${hijriDate}\n🤖 Generated by MIA - My Islam AI`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Daily Islamic Teaching',
          text: shareText,
        });
        toast.success('Shared successfully!');
      } catch (error) {
        if ((error as Error).name !== 'AbortError') {
          await navigator.clipboard.writeText(shareText);
          toast.success('Copied to clipboard!');
        }
      }
    } else {
      await navigator.clipboard.writeText(shareText);
      toast.success('Copied to clipboard!');
    }
  };

  const handleDownload = async () => {
    const currentCard = cards.get(currentIndex);
    if (!currentCard?.imageUrl) {
      toast.error('No image to download');
      return;
    }

    try {
      // Create a canvas to composite the image with text
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      const img = new Image();
      img.crossOrigin = 'anonymous';
      
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
        img.src = currentCard.imageUrl!;
      });

      canvas.width = 1080;
      canvas.height = 1920;

      // Draw background image
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

      // Add overlay
      ctx.fillStyle = 'rgba(0, 0, 0, 0.4)';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Add text
      const teaching = teachings[currentIndex];
      ctx.fillStyle = '#ffffff';
      ctx.textAlign = 'center';

      // Category badge
      ctx.font = 'bold 32px Arial';
      ctx.fillText(teaching.category.toUpperCase(), canvas.width / 2, 200);

      // Main quote
      ctx.font = '48px Georgia';
      const words = teaching.text.split(' ');
      let line = '';
      let y = canvas.height / 2 - 100;
      const maxWidth = canvas.width - 120;
      const lineHeight = 60;

      for (const word of words) {
        const testLine = line + word + ' ';
        const metrics = ctx.measureText(testLine);
        if (metrics.width > maxWidth && line !== '') {
          ctx.fillText(line.trim(), canvas.width / 2, y);
          line = word + ' ';
          y += lineHeight;
        } else {
          line = testLine;
        }
      }
      ctx.fillText(line.trim(), canvas.width / 2, y);

      // Source
      ctx.font = 'italic 28px Georgia';
      ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
      ctx.fillText(`— ${teaching.source}`, canvas.width / 2, y + 100);

      // Date
      ctx.font = '24px Arial';
      ctx.fillText(hijriDate, canvas.width / 2, canvas.height - 150);

      // MIA branding
      ctx.font = 'bold 28px Arial';
      ctx.fillStyle = '#FFD700';
      ctx.fillText('MIA • My Islam AI', canvas.width / 2, canvas.height - 80);

      // Download
      const link = document.createElement('a');
      link.download = `mia-teaching-${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();

      toast.success('Image downloaded!');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download image');
    }
  };

  if (teachings.length === 0) {
    return (
      <div className="bg-card rounded-3xl p-6 shadow-card border border-border animate-pulse">
        <div className="h-64 bg-muted rounded-2xl" />
      </div>
    );
  }

  const currentCard = cards.get(currentIndex);
  const teaching = teachings[currentIndex];

  return (
    <div className="relative bg-card rounded-3xl overflow-hidden shadow-card border border-border animate-slide-up" style={{ animationDelay: '0.2s' }}>
      {/* Header */}
      <div className="flex items-center justify-between p-3 border-b border-border/50">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-islamic-gold" />
          <span className="font-semibold text-sm text-foreground">Daily Teaching</span>
        </div>
        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="icon"
            onClick={regenerateImage}
            disabled={isGenerating || currentCard?.loading}
            className="h-7 w-7"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin' : ''}`} />
          </Button>
          <Button variant="ghost" size="icon" onClick={handleShare} className="h-7 w-7">
            <Share2 className="w-3.5 h-3.5" />
          </Button>
          <Button 
            variant="ghost" 
            size="icon" 
            onClick={handleDownload} 
            disabled={!currentCard?.imageUrl}
            className="h-7 w-7"
          >
            <Download className="w-3.5 h-3.5" />
          </Button>
        </div>
      </div>

      {/* Card Content - Fit to screen better */}
      <div className="relative h-[280px] overflow-hidden">
        {/* Background Image */}
        {currentCard?.loading ? (
          <div className="absolute inset-0 bg-gradient-to-br from-islamic-gold/20 via-secondary/20 to-primary/20 flex items-center justify-center">
            <div className="flex flex-col items-center gap-3">
              <div className="w-10 h-10 border-3 border-islamic-gold border-t-transparent rounded-full animate-spin" />
              <p className="text-sm text-muted-foreground">Generating artwork...</p>
            </div>
          </div>
        ) : currentCard?.imageUrl ? (
          <img
            src={currentCard.imageUrl}
            alt="Islamic teaching background"
            className="absolute inset-0 w-full h-full object-cover"
          />
        ) : (
          <div className="absolute inset-0 bg-gradient-to-br from-islamic-gold/30 via-secondary/20 to-primary/30" />
        )}

        {/* Overlay */}
        <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-black/30 to-black/60" />

        {/* Content */}
        <div className="relative h-full flex flex-col items-center justify-center p-4 text-white text-center">
          {/* Category Badge */}
          <span className="px-2.5 py-0.5 bg-islamic-gold/90 text-black text-[10px] font-bold rounded-full mb-3">
            {teaching?.category}
          </span>

          {/* Quote */}
          <p className="text-sm md:text-base font-serif leading-relaxed mb-3 max-w-[95%] line-clamp-4">
            "{teaching?.text}"
          </p>

          {/* Source */}
          <p className="text-xs text-white/80 italic">
            — {teaching?.source}
          </p>

          {/* Date & Branding */}
          <div className="absolute bottom-3 left-0 right-0 text-center">
            <p className="text-[10px] text-white/70 mb-0.5">{hijriDate}</p>
            <p className="text-[10px] font-bold text-islamic-gold">MIA • My Islam AI</p>
          </div>
        </div>

        {/* Navigation Arrows */}
        <button
          onClick={goToPrevious}
          className="absolute left-1.5 top-1/2 -translate-y-1/2 w-7 h-7 rounded-full bg-black/40 flex items-center justify-center text-white hover:bg-black/60 transition-colors"
        >
          <ChevronLeft className="w-4 h-4" />
        </button>
        <button
          onClick={goToNext}
          className="absolute right-1.5 top-1/2 -translate-y-1/2 w-7 h-7 rounded-full bg-black/40 flex items-center justify-center text-white hover:bg-black/60 transition-colors"
        >
          <ChevronRight className="w-4 h-4" />
        </button>
      </div>

      {/* Dots Indicator */}
      <div className="flex items-center justify-center gap-1 py-2">
        {teachings.slice(0, 5).map((_, idx) => (
          <button
            key={idx}
            onClick={() => setCurrentIndex(idx)}
            className={`w-1.5 h-1.5 rounded-full transition-all ${
              idx === currentIndex % 5 
                ? 'w-5 bg-islamic-gold' 
                : 'bg-muted-foreground/30 hover:bg-muted-foreground/50'
            }`}
          />
        ))}
        {teachings.length > 5 && (
          <span className="text-[10px] text-muted-foreground ml-1">+{teachings.length - 5}</span>
        )}
      </div>
    </div>
  );
};

export default DailyTeachingsCarousel;
